package com.paci.training.android.xungvv.mockprojectserver.data_local;

import com.paci.training.android.xungvv.mockprojectserver.model.Fruit;

import java.util.ArrayList;
import java.util.List;

public class FruitEntity {
    public static List<Fruit> getFruits(){
        List<Fruit> list = new ArrayList<>();
        list.add(new Fruit(1, "Tomato", "It includes seeds, the tomato is technically a fruit, contrary to popular belief. They are grown in more significant quantities than any other fruit, with over 170 million tons produced worldwide each year. Additionally, Tomatoes are low in calories and high in vitamins C and K, potassium, folate, and an antioxidant called lycopene."));
        list.add(new Fruit(2, "Banana", "Bananas are also one of the most popular fruits in the world. Almost 150 million bananas are produced (predominantly in India and China). Additionally, bananas, first and foremost, are abundant in potassium, which may help avoid strokes, high blood pressure, and heart disease."));
        list.add(new Fruit(3, "Apple", "Apples are grown mainly in China, the United States, Europe, and Turkey and are among the most popular fruits in the world. Every year, around 76 million tons are manufactured around the world. Additionally, Apple flavonoids such as quercetin, kaempferol, and catechin have antioxidant characteristics that can help protect against chronic illnesses like cancer, heart disease, and diabetes."));
        list.add(new Fruit(4, "Watermelon", "Watermelons are grown in most countries like South Africa, Japan, China, Turkey, India, Brazil, and other Part of the world. Additionally, China now leads the world in watermelon production, with roughly 73 million tonnes produced each year. Because of their natural sweetness and high water content, watermelons are frequently utilized in alcoholic and non-alcoholic cocktails. "));
        list.add(new Fruit(5, "Orange", "About 73 million oranges are produced in Brazil, China, India, and other countries. Vitamin B1, folic acid, and potassium are abundant in these bright tiny citrus fruits. Additionally, most orange crops manufacture orange juice, which is one of the most popular fruit drinks ever. A single serving of orange juice contains 67 percent of the daily required vitamin C requirement."));
        list.add(new Fruit(6, "Mango","Mangoes are also one of the most popular fruits in the world. India, China, and Thailand are the world’s top mango producers, with over 50 million tons of exotic tropical fruit produced each year. Additionally, mangoes are also high in copper, folate, niacin, potassium, riboflavin, manganese, thiamine, magnesium, dietary fiber, copper, folate niacin, potassium, riboflavin, manganese, thiamine, and magnesium."));
        list.add(new Fruit(7, "Pear", "Pears are unique in that they are native to many parts of the world, including much of Europe, Asia, and northern Africa. China remains the world’s largest producer of pears, with about 16 million metric tons produced each year. Additionally, they are a delicious and inexpensive delight available at street markets and supermarket shelves.  "));
        list.add(new Fruit(8, "Avocado", "Avocadoes are also one of the most popular fruits in the world. Avocados are a native fruit that originated in South-Central Mexico between 8000 and 5000 BCE and were domesticated by the indigenous 5,000 years ago. Additionally, avocadoes are a unique supply of fatty acids in fruits, providing approximately half of the required daily intake of healthy fats. While still being a rich source of fiber."));
        list.add(new Fruit(9, "Grape", "A grape is a berry-like fruit found on the deciduous woody vines of the Vitis genus of flowering plants. Additionally, grapes might be a decent option for snacks like cookies and sweets if you’re trying to cut down on processed foods or added sugars."));
        list.add(new Fruit(10,"Pineapple", "The Pineapple (Ananas comosus) is the most economically significant plant in the Bromeliaceae family. And also one of the most popular fruits in the world. It is a tropical plant with edible fruit. The Pineapple is native to South America, where it has been grown for hundreds of years. Additionally, Pineapple gets most of its calories from carbs, like most fruits. Pineapple isn’t a very high-protein food."));
        list.add(new Fruit(11, "Peach", "The peach (Prunus persica) is a deciduous tree native to Northwest China, where it was first domesticated and grown between the Tarim Basin and the north slopes of the Kunlun Mountains. Peaches can be used to replace more dangerous added sugars in sweets and pastries. Furthermore, peaches have a high level of vitamin C."));
        list.add(new Fruit(12, "Pumpkin", "Pumpkin is the 12th most popular fruit in the world. A pumpkin is a winter squash cultivar that is round with smooth, slightly ribbed SkinSkin and is often deep yellow to orange in color. Additionally, Pumpkin includes antioxidants such as alpha-carotene, beta-carotene, beta-cryptoxanthin, and others that may help protect your cells from free radical damage. "));
        list.add(new Fruit(13,"Dates", "Dates are one of the sweetest fruits on the planet. So it is no surprise that it is also one of the most popular fruits in the world. Dates are primarily grown in Egypt, Iran, Iraq, and Saudi Arabia, among other countries. Additionally, dates are naturally delicious, but they also include essential minerals and fiber as a fruit."));
        list.add(new Fruit(14,"Papaya", "Papayas thrive in tropical areas, often called papaws or pawpaws. Papaya is grown chiefly in India, Mexico, Brazil, Indonesia, Dominican Republic. They are among the most popular fruits globally because of their sweet taste, brilliant color, and wide range of health advantages."));
        list.add(new Fruit(15, "Strawberry", "Strawberries are high in antioxidants and plant compounds to help heart health and blood sugar management. These berries are typically eaten raw and fresh, but they can also be used in jams, jellies, and desserts. In addition, vitamin C, manganese, folate (vitamin B9), and potassium are all found in strawberries."));
        return list;
    }
}
